services:
  # TODO add librechat wired to rag-server and ollama. set up librechat.yaml

  rag-server:
    container_name: rag-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GRAPHDB_ENDPOINT: http://graphdb:7200/repositories/rag
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: llama3
      EMBEDDING_MODEL: // TODO add model
    volumes:
      - './bin/rag-server:/app/bin/rag-server:ro'
    depends_on:
      - graphdb
      - ollama

  graphdb:
    image: mirror.gcr.io/ontotext/graphdb:10.5.0-free
    restart: unless-stopped
    environment:
      - GDB_JAVA_OPTS=-Xmx1g
    volumes:
      - graphdb-data:/opt/graphdb/home
      - ./graphdb-config/data:/data

  ollama:
    image: mirror.gcr.io/ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  graphdb-data:
  ollama-data:
