[tools]
go = "1.25"
"go:github.com/ogen-go/ogen/cmd/ogen" = "v1.14.0"
golangci-lint = "2.4.0"

[tasks.default]
run = [
    { task = "generate" },
    { task = "modules" },
    { task = "build" },
    { task = "lint" },
]

[tasks.generate]
run = "ogen --target api/server/ragapi --package ragapi --config api/server/ragapi/.ogen.yml --clean api/server/ragapi.yaml"

[tasks.modules]
run = "go mod tidy"

[tasks.build]
run = "go build -trimpath -v -o ./bin/rag-server ./cmd/rag-server"

[tasks.lint]
run = "golangci-lint run"
